name: cody krieger

markdown: redcarpet
pygments: true

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'Procfile', 'Rakefile', 'config.ru', 'vendor', 'bin']

permalink: '/:year/:month/:day/:title/'
