exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'Procfile', 'Rakefile', 'config.ru', 'vendor', 'bin']

gems:
  - jemoji

name: 'cody krieger'
description: 'writings on software, technology, and most anything else'
url: https://krieger.io

excerpt_separator: "<!--more-->"

highlighter: pygments

permalink: '/:title/'
paginate: 7
paginate_path: '/page/:num/'
