exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'Procfile', 'Rakefile', 'config.ru', 'vendor', 'bin']

gems:
  - jemoji

name: cody krieger

markdown: redcarpet
highlighter: pygments

permalink: '/:title/'
paginate: 7
paginate_path: '/page/:num/'
