name: cody krieger

markdown: redcarpet
highlighter: pygments

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'Procfile', 'Rakefile', 'config.ru', 'vendor', 'bin']

permalink: '/:title/'

paginate: 7
paginate_path: '/page/:num/'
