baseURL = "https://new.krieger.io"
languageCode = "en-us"
title = "cody krieger"
copyright = "(c) 2020 cody krieger. all rights reserved."

ignoreErrors = ["error-disable-taxonomy"]
disableKinds = ["section", "taxonomy"]

[params]
  author = "cody krieger"
  description = "The personal website and blog of Cody Krieger."

[author]
  email = "cody@krieger.io"
  name = "cody krieger"

[output]
  home = ["HTML"]
  page = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "/rss/index"

[permalinks]
  pages = "/:filename/"
  posts = "/:filename/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
